# Generated by Django 4.2.7 on 2025-11-01 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('animal', 'Animal'), ('tracking', 'Tracking'), ('observation', 'Observation'), ('prediction', 'Prediction')], max_length=50)),
                ('local_id', models.UUIDField()),
                ('server_id', models.UUIDField(blank=True, null=True)),
                ('data', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('completed', 'Completed'), ('failed', 'Failed'), ('conflict', 'Conflict')], max_length=50)),
                ('conflict_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('attempts', models.IntegerField(default=0)),
                ('offline_since', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_queue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sync_queue',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=255)),
                ('total_items', models.IntegerField()),
                ('synced_items', models.IntegerField()),
                ('conflict_items', models.IntegerField()),
                ('failed_items', models.IntegerField()),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sync_logs',
                'ordering': ['-started_at'],
                'managed': True,
            },
        ),
    ]
