# Generated by Django 4.2.7 on 2025-11-07 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animals', '0002_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WildlifeAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('high_risk_zone', 'High Risk Zone Entry'), ('poaching_risk', 'Potential Poaching Activity'), ('corridor_exit', 'Left Wildlife Corridor'), ('rapid_movement', 'Rapid/Unusual Movement'), ('low_battery', 'Low Collar Battery'), ('weak_signal', 'Weak Signal Strength'), ('stationary_too_long', 'Animal Stationary Too Long'), ('unusual_behavior', 'Unusual Behavior Detected')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('false_alarm', 'False Alarm')], default='active', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='animals.animal')),
                ('conflict_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='core.conflictzone')),
            ],
            options={
                'db_table': 'wildlife_alerts',
                'ordering': ['-detected_at'],
                'managed': True,
                'indexes': [models.Index(fields=['animal', '-detected_at'], name='wildlife_al_animal__ace4dd_idx'), models.Index(fields=['status', 'severity'], name='wildlife_al_status_1c2514_idx'), models.Index(fields=['alert_type', 'status'], name='wildlife_al_alert_t_a2a479_idx')],
            },
        ),
    ]
