# Generated by Django 4.2.7 on 2025-11-01 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corridor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('species', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('planned', 'Planned'), ('under_review', 'Under Review')], max_length=50)),
                ('start_point', models.JSONField()),
                ('end_point', models.JSONField()),
                ('path', models.JSONField(blank=True, null=True)),
                ('optimization_score', models.FloatField(blank=True, null=True)),
                ('optimization_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_corridors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'corridors',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
