# Generated by Django 4.2.7 on 2025-11-05 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RangerTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Ranger Teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ranger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('badge_number', models.CharField(max_length=50, unique=True)),
                ('emergency_contact', models.CharField(blank=True, help_text='Emergency contact person (family/supervisor)', max_length=20)),
                ('current_status', models.CharField(choices=[('on_duty', 'On Duty'), ('off_duty', 'Off Duty'), ('on_leave', 'On Leave'), ('emergency_response', 'Emergency Response')], default='off_duty', max_length=20)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, help_text='Mobile device or GPS tracker ID', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rangers', to='rangers.rangerteam')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranger_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__name'],
            },
        ),
        migrations.CreateModel(
            name='PatrolRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('waypoints', models.JSONField(help_text='Array of {lat, lon, name} waypoints')),
                ('estimated_duration_hours', models.FloatField()),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_rangers', models.ManyToManyField(related_name='assigned_routes', to='rangers.ranger')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_routes', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrol_routes', to='rangers.rangerteam')),
            ],
            options={
                'ordering': ['-scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='RangerTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True)),
                ('speed_kmh', models.FloatField(blank=True, null=True)),
                ('directional_angle', models.FloatField(blank=True, null=True)),
                ('activity_type', models.CharField(choices=[('patrolling', 'Patrolling'), ('stationary', 'Stationary'), ('responding', 'Responding to Incident'), ('resting', 'Resting'), ('traveling', 'Traveling')], default='patrolling', max_length=20)),
                ('battery_level', models.CharField(blank=True, help_text='Device battery percentage or status', max_length=50)),
                ('signal_strength', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ranger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_points', to='rangers.ranger')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ranger', '-timestamp'], name='rangers_ran_ranger__b00abb_idx'), models.Index(fields=['timestamp'], name='rangers_ran_timesta_74ea18_idx')],
            },
        ),
        migrations.CreateModel(
            name='PatrolLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_type', models.CharField(choices=[('patrol_start', 'Patrol Start'), ('patrol_end', 'Patrol End'), ('animal_sighting', 'Animal Sighting'), ('emergency', 'Emergency'), ('incident', 'Incident'), ('checkpoint', 'Checkpoint'), ('rest_break', 'Rest Break'), ('other', 'Other')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('photo_url', models.URLField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ranger_logs', to='animals.animal')),
                ('ranger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrol_logs', to='rangers.ranger')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_logs', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrol_logs', to='rangers.rangerteam')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['log_type', '-timestamp'], name='rangers_pat_log_typ_f18108_idx'), models.Index(fields=['priority', 'is_resolved'], name='rangers_pat_priorit_9a8e3e_idx')],
            },
        ),
    ]
