# Generated by Django 4.2.7 on 2025-11-01 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('local_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('collar_id', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('speed_kmh', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('battery_level', models.FloatField(blank=True, null=True)),
                ('signal_strength', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('activity_type', models.CharField(blank=True, choices=[('resting', 'Resting'), ('feeding', 'Feeding'), ('moving', 'Moving'), ('unknown', 'Unknown')], max_length=50, null=True)),
                ('source', models.CharField(choices=[('gps', 'GPS'), ('manual', 'Manual'), ('imported', 'Imported')], max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('synced', models.BooleanField(default=False)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_data', to='animals.animal')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_tracking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tracking',
                'ordering': ['-timestamp'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('local_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('observation_type', models.CharField(choices=[('sighting', 'Sighting'), ('behavior', 'Behavior'), ('health', 'Health'), ('environment', 'Environment')], max_length=50)),
                ('description', models.TextField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('photo_url', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('synced', models.BooleanField(default=False)),
                ('animal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='animals.animal')),
                ('observer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'observations',
                'ordering': ['-timestamp'],
                'managed': True,
            },
        ),
    ]
