# Generated by Django 4.2.7 on 2025-11-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_tracking_field_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='directional_angle',
            field=models.FloatField(blank=True, help_text='Direction of movement in degrees (0-360)', null=True),
        ),
    ]
